### PR TITLE
get paras on error case

### PR DESCRIPTION
**Pull request by saaavsaaa**
I need to get the parameters of the method that throws the exception.

---
This change is [Reviewable](https://reviewable.io/reviews/btraceio/btrace/311)

### CODE REVIEW

**Comment by saaavsaaa** [comment]
I saw it wrong again, and clicked -_-||

**Comment by jbachorik** [comment]
Please, take a look at eg. `SYNC_EXIT` [implementation ](https://github.com/btraceio/btrace/blob/master/src/share/classes/com/sun/btrace/runtime/Instrumentor.java#L1546)
Similarly to capturing the monitor object there you should use `getTargetInstanceParameter()` to indicate the method argument capturing the caught throwable. The code will end up being pretty similar - it would dup-store the value on the stack to a temporary variable and then load that variable to `getTargetInstanceParameter()`-th method argument. The rest of the validation and argument handling will be the same.

**Comment by saaavsaaa** [comment]
OK, I'll learn the code carefully.

**Comment by saaavsaaa** [comment]
It seems to be unable to work well.I think maybe I should commit modification after my totally understanding of the whole project. And I am doing this.

**Comment by jbachorik** [comment]
Duplicated by #327

**Pull request closed without merging**
