### PR TITLE
Tracing code remotely

### PR DESCRIPTION
**Pull request by gawaine1988**
Add the function that could trace code remotely by simplely adds a command line parameter: -ip.

---
This change is [Reviewable](https://reviewable.io/reviews/btraceio/btrace/359)

### CODE REVIEW

**Comment by gawaine1988** [comment]
ok, it seems that my English is not good,  however there is no need to talk dirty

**Comment by yardus** [comment]
Dirty?

**Comment by gawaine1988** [comment]
I am sorry that I misunderstood the meaning of 'nit'. I thought 'nit' meant 'stupid'.
And thanks for your comment.

**Comment by yardus** [comment]
Ok. Got a bit surprised :) 'nit' - a small comment, not necessary blocking the merge

**Comment by jbachorik** [comment]
Can you, please, address the comments so I can merge the changes?

**Comment by codeMonkeyLife** [comment]
why don't merge this request please? I think it is neccessry to trace remote program as far as I am concerned.

**Comment by gawaine1988** [comment]
| |
撒网
邮箱：gawaine1988@163.com
|

签名由 网易邮箱大师 定制

On 09/29/2018 17:02, Jaroslav Bachorik wrote:

Can you, please, address the comments so I can merge the changes?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.




Sorry , I will do that as soon as possible

**Comment by gawaine1988** [comment]
Thank you jbachorik. 
I apologize for the late.

**Comment by gawaine1988** [comment]
Sorry, I haven't pulled request before. Now, I address the comments and rebuild the project successfully on my pc.
Thank you for reviewing my code.

**Comment by gawaine1988** [comment]
If there are still problems, please comment, I will finish it tomorrow.

**Comment by gawaine1988** [comment]
Hellow jbachorik, I removed the validation of the parameter 'host'.
And, what's more , I also removed the validation of the attachment of btrace-agent.

**Comment by gawaine1988** [comment]
hello, jbachorik, I have removed the validation for the 'host'

**Comment by jbachorik** [comment]
Hi @gawaine1988, sorry for the late reply, was caught in busy work. PR is merged now.
Thanks again for contributing!

**Pull request merged**
