### PR TITLE
get paras on error case

### PR DESCRIPTION
**Pull request by saaavsaaa**
I need to get the parameters of the method that throws the exception.

---
This change is [Reviewable](https://reviewable.io/reviews/btraceio/btrace/308)

### CODE REVIEW

**Comment by saaavsaaa** [comment]
It(conclude unit test) works well in my local environment, and I can't fix it.

**Comment by yardus** [comment]
Why can't you fix? It was a good start - it would require few refinements but could have been a proper feature ...

**Comment by saaavsaaa** [comment]
Thank，I will try to fix it.It may just take a long time.

**Comment by saaavsaaa** [comment]
My master branch was changed disorderly by me, and I commited a new request
https://github.com/btraceio/btrace/pull/311

**Pull request closed without merging**
